### ISSUE TITLE
As a player, I want to create an account, so that I can save my progress and compete with others

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#1]
- [x] sopra-fs24-group-23/sopra24_client#25
- [x] sopra-fs24-group-23/sopra24_server#20
- [x] sopra-fs24-group-23/sopra24_client#26
- [x] sopra-fs24-group-23/sopra24_client#2
