### ISSUE TITLE
As the game host in the lobby, I want to be able to manage other users in order to kick them if necessary

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#10]
- [x] sopra-fs24-group-23/sopra24_client#35
- [x] sopra-fs24-group-23/sopra24_client#34
- [x] sopra-fs24-group-23/sopra24_server#64
- [x] sopra-fs24-group-23/sopra24_client#33
- [x] sopra-fs24-group-23/sopra24_client#32
