### ISSUE TITLE
As a player, I want to view my historical performance and compare it with others on a global leaderboard, so that I can track my progress and aim for higher rankings

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#11]
- [x] sopra-fs24-group-23/sopra24_client#9
- [x] sopra-fs24-group-23/sopra24_client#10
- [ ] sopra-fs24-group-23/sopra24_server#34
- [ ] sopra-fs24-group-23/sopra24_server#83
- [x] sopra-fs24-group-23/sopra24_server#84

**Comment by nilshgt** [comment]
https://github.com/sopra-fs24-group-23/sopra24_server/commit/57ffc9a9d412d76574926c75f0ea295ced857a93
