### ISSUE TITLE
As a player, I want to customize my profile, so that I can have a personalized experience

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#12]
- [x] sopra-fs24-group-23/sopra24_client#23
- [x] sopra-fs24-group-23/sopra24_client#24
- [x] sopra-fs24-group-23/sopra24_client#22
- [x] sopra-fs24-group-23/sopra24_server#82
- [x] #115
