### ISSUE TITLE
As a player in-game I want the option to leave the game and be redirected back to the homepage

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs24-group-23/sopra24_server#139]
- [x] sopra-fs24-group-23/sopra24_client#122
- [x] sopra-fs24-group-23/sopra24_server#141
- [x] sopra-fs24-group-23/sopra24_server#142
- [x] sopra-fs24-group-23/sopra24_server#143
- [x] sopra-fs24-group-23/sopra24_server#144
