### ISSUE TITLE
As a player in a lobby I want to be able to leave the lobby so I am able to swap lobbies

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#14]
- [x] sopra-fs24-group-23/sopra24_client#21
- [ ] sopra-fs24-group-23/sopra24_server#75
- [x] sopra-fs24-group-23/sopra24_client#1
- [x] sopra-fs24-group-23/sopra24_server#128

**Comment by nilaksan97** [comment]
6d944dd0be44078eb60f970cd6ee69930f3b75e8
