### ISSUE TITLE
As a player while inputting answers I want to be able to use a joker for a category to score with a fake answer

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs24-group-23/sopra24_server#16]
- [x] sopra-fs24-group-23/sopra24_client#28
- [x] sopra-fs24-group-23/sopra24_client#88
- [x] sopra-fs24-group-23/sopra24_server#39
