### ISSUE TITLE
As a user in the lobby, I want an option to randomize categories, so I can have different categories each round

### ISSUE THREAD

**Issue by Dedphish** [sopra-fs24-group-23/sopra24_server#193]
- [x] sopra-fs24-group-23/sopra24_client#130
- [x] sopra-fs24-group-23/sopra24_client#131
- [x] sopra-fs24-group-23/sopra24_server#196

**Comment by Dedphish** [comment]
closed, see tasks for commits
