### ISSUE TITLE
As a registered player, I want to login to my existing account, so that I can access my saved progress and compete with others

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#2]
- [x] sopra-fs24-group-23/sopra24_client#27
- [x] sopra-fs24-group-23/sopra24_server#24
- [x] sopra-fs24-group-23/sopra24_client#4
- [x] sopra-fs24-group-23/sopra24_client#3
- [x] sopra-fs24-group-23/sopra24_client#5
- [x] sopra-fs24-group-23/sopra24_client#61
