### ISSUE TITLE
As a (logged in) player, I want to access the homepage to host a new lobby or join a lobby.

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#3]
- [x] sopra-fs24-group-23/sopra24_client#17
- [x] sopra-fs24-group-23/sopra24_client#46
- [x] sopra-fs24-group-23/sopra24_server#47
- [x] sopra-fs24-group-23/sopra24_client#29
- [x] sopra-fs24-group-23/sopra24_client#19
- [x] sopra-fs24-group-23/sopra24_client#18
- [ ] sopra-fs24-group-23/sopra24_client#20
- [x] sopra-fs24-group-23/sopra24_server#93
- [x] sopra-fs24-group-23/sopra24_client#51

**Comment by nilaksan97** [comment]
64d9364db0b3da50c89e39fd7b84c001d724f479
