### ISSUE TITLE
As a logged in player, I want to be able to host and customize a lobby to set up a game

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#4]
- [x] sopra-fs24-group-23/sopra24_client#45
- [x] sopra-fs24-group-23/sopra24_client#73
- [x] sopra-fs24-group-23/sopra24_client#44
- [x] sopra-fs24-group-23/sopra24_client#43
- [x] sopra-fs24-group-23/sopra24_client#42
- [x] sopra-fs24-group-23/sopra24_client#41
- [x] sopra-fs24-group-23/sopra24_client#62
- [x] sopra-fs24-group-23/sopra24_client#74
