### ISSUE TITLE
As a logged-in player, I want to be able to log out from my account, so I can exit the application

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#5]
- [x] sopra-fs24-group-23/sopra24_client#6
- [x] sopra-fs24-group-23/sopra24_client#8
- [x] sopra-fs24-group-23/sopra24_server#101

**Comment by fr4n715k4** [comment]
d85ec5e4db2d5124654d5790a07a1d12008b8814

138177a0d4f7e7c2f2192854bfb248190b6b0257
