### ISSUE TITLE
As a player during game-phases, I want to have a timer that indicates how much time is left for the current phase 

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#6]
- [x] sopra-fs24-group-23/sopra24_client#52
- [x] sopra-fs24-group-23/sopra24_client#39
- [x] sopra-fs24-group-23/sopra24_server#94
- [x] sopra-fs24-group-23/sopra24_client#54
- [x] sopra-fs24-group-23/sopra24_client#53
- [x] #116
