### ISSUE TITLE
As a player in between rounds I want to see a scoreboard showing which of my answers were right and total scores, so that I know where I currently rank

### ISSUE THREAD

**Issue by fr4n715k4** [sopra-fs24-group-23/sopra24_server#77]
- [x] sopra-fs24-group-23/sopra24_client#11
- [x] sopra-fs24-group-23/sopra24_client#12
- [x] sopra-fs24-group-23/sopra24_server#84
- [x] sopra-fs24-group-23/sopra24_server#91
